.PHONY: help

test:
	go test -v ./

help:
	@echo "Usage: make [target]"
	@echo "This Makefile is used to manage test, build, run and clean process of the project."
	@echo "It contains the following targets:"
	@echo
	@echo "  test   - Run all example tests"
	@echo